Added various programming language question generation in Expression DT domain with MeaningTree
procudin/OntoQuiz pull request #350
Opened 2024-11-09 20:37 UTC by brookite

What hasn't been implemented yet:
- Getting next correct question answer
- ...

2024-11-19 08:37 UTC, procudin requested changes

2024-11-19 08:37 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +public abstract class DomainToBackendInterface<BackendInput, BackendOutput, Back extends Backend<BackendInput, BackendOutput>> {
лучше назвать `DomainToBackendAdapter`

2024-11-19 08:37 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java
> +    }
Что-то сходу непонятно, что тут происходит. Почему мапа, мы хотим чтобы домен поддерживал несколько бэкендов? Если да, то заменить на что-то нормальное, что-то вроде
```java
public abstract DomainToBackendInterface<?, ?, ?> getBackendAdapter(String backendId);
```
Чтобы не использовать Backend<?, ?> как ключ мапы, чтобы не было этих костылей с AopProxyUtils
Пусть домены сами решают, что им нужно, дефолтную реализацию не нужно делать

2024-11-19 08:37 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +    }
убрать, адаптер не должен использоваться в мапах как ключ (см. коммент в Domain)

2024-11-19 10:28 UTC, brookite commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +    }
@Max-Person это касается твоей части работы

2024-11-22 19:50 UTC, Max-Person commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java
> +    }
Использование классов позволяет гарантировать правильную типизацию адаптеров с бэкендами.
Если адаптеры будут знать только про id бэкенда, ничто не мешает разработчику сделать неправильную типизацию.

Мапа снаружи в любом случае не видна, виден только метод getBackendInterface, который как раз аналогичен первой строке того, что ты написал в своем предложении.

2024-11-22 19:54 UTC, Max-Person commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +    }
Во первых - что значит "убрать", с чего бы? equals и hashcode является частью стандартных контрактов классов. Переопределять их в соответствии со смыслом самого класса - хороший тон.
Во вторых - адаптеры и не используются в мапах как ключ (сравниваются только внутри сетов)

2024-11-23 13:16 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java
> +    }
1. Типизация и так уже утеряна, везде `<?>`, все равно будет в конце концов каст на котором все свалится. Я еще могу согласиться с передачей явного типа бэкенда как аргумент, но уж точно не использованию его как ключа в мапе и вот этот `AopProxyUtils`. Ключем должен быть backendId.
Тогда разницы между 
```java
DomainToBackendInterface<?, ?, ?> getBackendInterface(Backend<?, ?> backend) {
    var backendId = backend.getId();
    return backendClassToInterfaceMap.get(backendId);
}
``` 
и
```java
DomainToBackendInterface<?, ?, ?> getBackendInterface(String backendId) {
    return backendClassToInterfaceMap.get(backendId);
}
``` 
не будет никакой, просто вторая версия более очевидная.

2. это некритично, можно и оставить мапу, это просто моя вкусовщина 
3. аналогично

2024-11-23 13:25 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +    }
`Во первых - что значит "убрать", с чего бы? equals и hashcode является частью стандартных контрактов классов. Переопределять их в соответствии со смыслом самого класса - хороший тон.`

Не согласен. Переопределять их это не хороший тон, а явное объявление потенциальных сценариев использования, в которых объекты либо могут сравниваться друг с другом, либо использоваться в качестве ключа хешмапы. И я против такого использования, адаптер должен быть тупым. Плюс реализация крайне неочевидная.

2024-12-31 08:02 UTC, procudin requested changes

2024-12-31 08:02 UTC, procudin commented on modules/core/src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-dt-messages_en.properties
> +expr_domain_dt.student_end_evaluation=everything is evaluated
нужно добавить перенос строки перед EOF

2024-12-31 08:02 UTC, procudin commented on modules/server/src/test/java/org/vstu/compprehension/models/businesslogic/ProgrammingLanguageExpressionDTDomainTest.java
> +    }
не только нужно подчистить то, что явно создалось, но и то, что неявно в процессе работы тестов нагенерилось

2024-12-31 08:06 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/DomainToBackendInterface.java
> +    }
@Max-Person @brookite что по исправлению?

2024-12-31 08:07 UTC, procudin commented on modules/core/src/main/java/org/vstu/compprehension/Service/QuestionService.java
> +        return usedInterface.interpretJudgeOutput(question, output);
кст тогда вообще уйдет нужда в вынесении `getBackendInterface` в контракт домена и решится проблема, которая мне не нравилась в первом ревью

2025-01-07 21:47 UTC, brookite commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDTDomain.java
> +        );
Это не относится к моей части работы. Каким-то образом попали коммиты @den1s0v

2025-01-12 20:26 UTC, den1s0v commented on modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDTDomain.java
> +        );
Не сломает. Этот метод не используется и, вероятно, будет удалён.

2025-01-12 20:26 UTC, den1s0v commented on modules/server/src/test/java/org/vstu/compprehension/models/businesslogic/ControlFlowStatementsDomainTest.java
Удалён

2025-01-12 20:34 UTC, den1s0v commented on modules/core/src/main/java/org/vstu/compprehension/Service/QuestionService.java
> +        return usedInterface.interpretJudgeOutput(question, output);
Вообще, разумно. 
Изначальная мысль о том, чтобы любой домен мог обсчитываться на любом бэкенде, на уровне реализации странновата. Мы теперь знаем, что универсальных ризонеров не бывает. 
Поддерживаю идею, что связать домен с бэкендом лучше явно, чем костыльно.
Это — к общей структуре потока данных и соответствующих java-интерфейсов в проекте.

2025-03-22 10:18 UTC, procudin approved these changes

2025-03-22 10:32 UTC, merged